### ISSUE TITLE
Fresh docker node-red install:  flows Stopped  due to missing node types.

### ISSUE THREAD

**Issue by sudoritz** [simonradier/node-red-contrib-selenium-wd2#1]
i only installed this package 

Flows stopped due to missing node types.

open-web
screenshot
close-web

<img width="891" alt="Screen Shot 2020-10-23 at 9 33 22 AM" src="https://user-images.githubusercontent.com/9424289/97023658-0ce79e80-1513-11eb-81b3-38e6b39ba54f.png">

**Comment by simonradier** [comment]
Hi Sudoritz,

Could you share with me the starting logs of your node-red server? I tried a fresh install and was not able to reproduce it.
Can you share with me the version of the following components : 
* Node
* Node-red

And the OS you are using.

Thanks!

**Comment by sudoritz** [comment]
https://hub.docker.com/r/nodered/node-red/


docker run -it -p 2222:2222 -v /opt/nodered:/data --name nodered nodered/node-red

> node-red-docker@1.0.6 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"

23 Oct 15:15:13 - [info]

Welcome to Node-RED
===================

23 Oct 15:15:13 - [info] Node-RED version: v1.0.6
23 Oct 15:15:13 - [info] Node.js  version: v10.20.1
23 Oct 15:15:13 - [info] Linux 3.10.0-957.10.1.el7.x86_64 x64 LE
23 Oct 15:15:14 - [info] Loading palette nodes
23 Oct 15:15:14 - [info] Settings file  : /data/settings.js
23 Oct 15:15:14 - [info] Context store  : 'default' [module=memory]
23 Oct 15:15:14 - [info] User directory : /data

==installing it===

23 Oct 15:59:37 - [info] Installing module: node-red-contrib-selenium-wd2, version: 0.1.2
23 Oct 15:59:44 - [info] Installed module: node-red-contrib-selenium-wd2
23 Oct 15:59:44 - [info] Added node types:
23 Oct 15:59:44 - [info]  - node-red-contrib-selenium-wd2:click-on : Error: Cannot find module 'fs/promises'
23 Oct 15:59:44 - [info]  - node-red-contrib-selenium-wd2:close-web : Error: Cannot find module 'fs/promises'
23 Oct 15:59:44 - [info]  - node-red-contrib-selenium-wd2:find-element : Error: Cannot find module 'fs/promises'
23 Oct 15:59:44 - [info]  - node-red-contrib-selenium-wd2:get-attribute : Error: Cannot find module 'fs/promises'
23 Oct 15:59:44 - [info]  - node-red-contrib-selenium-wd2:get-text : Error: Cannot find module 'fs/promises'
23 Oct 15:59:44 - [info]  - node-red-contrib-selenium-wd2:get-title : Error: Cannot find module 'fs/promises'

**Comment by sudoritz** [comment]
i also just updated  to v1.2.2 / node.js v10.22.1

23 Oct 16:37:41 - [info] Node-RED version: v1.2.2
23 Oct 16:37:41 - [info] Node.js  version: v10.22.1
23 Oct 16:37:41 - [info] Linux 3.10.0-957.10.1.el7.x86_64 x64 LE
23 Oct 16:37:41 - [info] Loading palette nodes
23 Oct 16:37:42 - [info] Settings file  : /data/settings.js

**Comment by sudoritz** [comment]
looking at  this  further   ( i do have  a separate  docker selenium/standalone-chrome) running :4444

`40c49b99bbf5        selenium/standalone-chrome   "/opt/bin/entry_po..."   5 months ago        Up 5 months               0.0.0.0:4444->4444/tcp             selenium-chrome`

but im seeing this below here  

In order to use node-red-contrib-selenium-wd2, you must fullfill the following prerequisite :

Install java 8 or later
Install a selenium server : npm install -g webdriver-manager
Install a node-red server : npm install -g --unsafe-perm node-red


i built this upon docker so could i just point to wd server or do i have to  install webdriver-manager also.)

**Comment by simonradier** [comment]
Ok, I found the issue. It seems that in node under version 14 there is a issue wih the import of "fs/promise". I modified it.
Please try using version 0.1.3.

And yes of course, you can just point to an external wd server ;)

**Comment by sudoritz** [comment]
i can confirm that fixed  it its now showing reachable and not failing on deploy. 👍

**Comment by simonradier** [comment]
Great!
