### ISSUE TITLE
Can/Does this use the Chrome selenium-stealth add-in?

### ISSUE THREAD

**Issue by bwims** [simonradier/node-red-contrib-selenium-wd2#19]
Hello,

The new Cloudflare turnstile makes it very hard to web scrape from Cloudflare sites.

I found [this](https://stackoverflow.com/questions/68289474/selenium-headless-how-to-bypass-cloudflare-detection-using-selenium) on stackoverflow which refers to a package which prevents cloudflare from detecting headless mode in the answer, and I wondered if you had implemented it.

Thanks!

B.

**Comment by simonradier** [comment]
Hi,

This repos should be closed. Could you reopen your request on this repo: https://github.com/simonradier/node-red-contrib-simple-webdriver

Thanks
