### ISSUE TITLE
Feature idea - Generate node-red node Flows via Selenium IDE .side file 

### ISSUE THREAD

**Issue by sudoritz** [simonradier/node-red-contrib-selenium-wd2#2]
I always thought this would be quite awesome to build onto  (i  was  trying  on puppeteer world  but never got  anywhere. 
but could you in theory Take a saved Selenium IDE json .side file  and load it somehow to  generate nodes  in node-red.  
https://www.selenium.dev/selenium-ide/

not sure if this will even work  end-end as there could be  nodes  not supporting all the IDEs  worth  a fun shot  to  ask :)

**Comment by simonradier** [comment]
Let focus on nodes stability first 😄. But it is a good idea!
