### ISSUE TITLE
msg.driver.session_.value_ not showing selenium session ID. theres many other driver/flow payload variables not  showing

### ISSUE THREAD

**Issue by sudoritz** [simonradier/node-red-contrib-selenium-wd2#4]
i dont know if this is causing anything else.  but  comparing original  selenium-wd vs wd2 i noticed when  viewing the payloadd i can see alot of flow/driver/sessionID info.  

also when on wd/hub/ page  wd2 doesnt let you take a  screenshot  in the flow or even delete  session (it does but does give you error) 

<img width="408" alt="Screen Shot 2020-10-24 at 7 33 27 PM" src="https://user-images.githubusercontent.com/9424289/97096924-9d67d100-1630-11eb-9928-eed6d4e04a83.png">

here is a view that  shows it not passing VAR inthe  payload  (not sure if that is pushing issues to wdHUB

<img width="1294" alt="Screen Shot 2020-10-24 at 7 33 09 PM" src="https://user-images.githubusercontent.com/9424289/97096932-b1133780-1630-11eb-93bb-341d8efdc14b.png">

**Here is  the original version that you can see full msg object with  session data tracking**

<img width="1082" alt="Screen Shot 2020-10-24 at 7 28 50 PM" src="https://user-images.githubusercontent.com/9424289/97096945-e9b31100-1630-11eb-8003-7894fec84023.png">

**Comment by simonradier** [comment]
Ok, it took me time to found it. It is based on the new version of selenium-webdriver (4.0.0-x-Alpha). It does not rely on flow system anymore (this is why you can't found it). 
=> It has a side effect where the session_ is not resolved as well (It was relying on flow as well and now relies on Promise)
You can use the `getSession` function of the driver to query the sessionId.

**Comment by sudoritz** [comment]
so  quick  question  so  to  get these Flow  Variables  back from  Session Responses  i would need to  update   my docker  to selenium-webdriver 4.0.0-x-Alpha). ?
