### ISSUE TITLE
Can't resize the instance 

### ISSUE THREAD

**Issue by olivier-dybox** [simonradier/node-red-contrib-selenium-wd2#5]
Hello, i use the example flow.json. The component "Open URL" raise the error "Cant' resize the instance of chrome" !

Have you a solution ?

Versions :
- NodeRed 0.20.8
- node-red-contrib-selenium-wd2 0.1.4-4
- selenium node v3 or v4 chrome or opera : same error
- Docker on mac osx

Can't resize the instance of chrome
(node:18) UnhandledPromiseRejectionWarning: TypeError: done is not a function
    at NodeOpenWebConstructor.<anonymous> (/data/node_modules/node-red-contrib-selenium-wd2/dist/nodes/open-web.js:113:21)
    at step (/data/node_modules/node-red-contrib-selenium-wd2/dist/nodes/open-web.js:33:23)
    at Object.next (/data/node_modules/node-red-contrib-selenium-wd2/dist/nodes/open-web.js:14:53)
    at fulfilled (/data/node_modules/node-red-contrib-selenium-wd2/dist/nodes/open-web.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9818)

**Comment by simonradier** [comment]
Dear Olivier,

(I know the error is not explicit), it is because you are using an old version of node-red (i.e <1.x). You must use at lease a 1.x version which provide the send / done function in the node execution which explains the `TypeError: done is not a function`. Could you try to update you node-red version and tell me if you still have the issue?

Simon,

**Comment by olivier-dybox** [comment]
Simon,  

I fixed my error on the docker source of node-red (nodered/node-red instead nodered/node-red-docker). I use now a node-red version 1.2.2 and all is ok. 

You have built a very interesting program for RPA tasks.

Thanks a lot.
Olivier

**Comment by simonradier** [comment]
You're welcome. Not my idea, just updated it 😄. I wanted to by a node-red node with limited dependency and written in typescript. I must admit I'll focus more on RPA than UI testing (which can be done with [node-red-contrib-wdio](https://flows.nodered.org/node/node-red-contrib-wdio).
