### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by Stefananderssonster** [simonradier/node-red-contrib-selenium-wd2#7]
Can this node package be used with raspberry pi?

**Comment by simonradier** [comment]
Hi Stefan,

Yes it could work on a raspberry. You may need to require to launch the browser in Headless mode. Do you use the raspberry as a desktop or as a server (only through SSH).

Simon,

**Comment by Stefananderssonster** [comment]
Hello Simon,

My intention is to use the raspberry pi headless and extract some data from
webpages that the http request node can't handle. I thought this could be a
easy way since I'm not a computer genius, I downloaded the wd2 nodes and
installed webdriver-manager but I think the chrome driver is giving me
problems.


Can't open an instance of chrome
SessionNotCreatedError: Unable to create new service:
ChromeDriverServiceBuild info: version: '3.141.59', revision: 'e82be7d358',
time: '2018-11-14T08:25:53'System info: host: 'iotcontroller', ip:
'127.0.1.1', os.name: 'Linux', os.arch: 'arm', os.version: '4.14.79-v7+',
java.version: '1.8.0_65'Driver info: driver.version: unknown

//Stefan

Den mån 7 dec. 2020 kl 12:34 skrev Critik <notifications@github.com>:

**Comment by simonradier** [comment]
You have to install Chrome on your raspberry as well. Let me know if it works after that :)
