### ISSUE TITLE
Getting all cookies?

### ISSUE THREAD

**Issue by vukmirovic98** [simonradier/node-red-contrib-selenium-wd2#8]
I am trying to get all of the saved cookies from the webdriver session.
I tried using a run script with a command `document.cookie`, but i can`t get all of the cookies.
I want to capture the password hash that is stored in a cookie[password_hashSSL], and while selenium itself haves the get/add/delete cookies function it will be realy usable inside node-red too.

**Comment by simonradier** [comment]
Hi @vukmirovic98 ,

Have you tried to run the following script `return document.cookie` it should work. I agree with you about cookie management, it'll come in a future release (after 0.2.x).

Simon,

**Comment by vukmirovic98** [comment]
Yes i managed to get cookies but haven`t realized that some of them were HTTP only :(
